[package]
name = "rust-ice-agent"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libnice-sys = "0.1.0"
libc = "0"
glib = "0"
